from PyQt5 import QtCore, QtGui, QtWidgets
from encrypt_check import Ui_encrypt_check
import sqlite3
class Ui_data_check(object):
    def setupUi(self, data_check, drug_List, each_drug, each_drug2, day_start, select_meal, updated_data2):
        self.data_check = data_check
        self.drug_List = drug_List
        self.each_drug = each_drug
        self.each_drug2 = each_drug2
        self.day_start = day_start
        self.select_meal = select_meal
        self.updated_data2 = updated_data2

        data_check.setObjectName("data_check")
        data_check.resize(531, 401)
        data_check.setStyleSheet("background-color: rgb(217, 244, 255)")
        self.centralwidget = QtWidgets.QWidget(data_check)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(115, 20, 325, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setLineWidth(1)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.add_back_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.add_back_pushButton.setGeometry(QtCore.QRect(20, 40, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.add_back_pushButton.setFont(font)
        self.add_back_pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(166, 0, 0)")
        self.add_back_pushButton.setObjectName("add_back_pushButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 80, 551, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(255, 170, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setLineWidth(1)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 200, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setLineWidth(1)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.drugDescribe_label = QtWidgets.QLabel(self.centralwidget)
        self.drugDescribe_label.setGeometry(QtCore.QRect(15, 140, 100, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.drugDescribe_label.setFont(font)
        self.drugDescribe_label.setObjectName("drugDescribe_label")
        self.drugAll_label = QtWidgets.QLabel(self.centralwidget)
        self.drugAll_label.setGeometry(QtCore.QRect(15, 170, 210, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.drugAll_label.setFont(font)
        self.drugAll_label.setObjectName("drugAll_label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 140, 150, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setLineWidth(1)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.drugName_label = QtWidgets.QLabel(self.centralwidget)
        self.drugName_label.setGeometry(QtCore.QRect(15, 110, 50, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.drugName_label.setFont(font)
        self.drugName_label.setObjectName("drugName_label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(255, 200, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setLineWidth(1)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.drugOne_label = QtWidgets.QLabel(self.centralwidget)
        self.drugOne_label.setGeometry(QtCore.QRect(15, 200, 232, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.drugOne_label.setFont(font)
        self.drugOne_label.setObjectName("drugOne_label")
        self.next_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.next_pushButton.setGeometry(QtCore.QRect(420, 275, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.next_pushButton.setFont(font)
        self.next_pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 127);\n"
"")
        self.next_pushButton.setObjectName("next_pushButton")
        self.drugStill = QtWidgets.QLabel(self.centralwidget)
        self.drugStill.setGeometry(QtCore.QRect(15, 260, 220, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.drugStill.setFont(font)
        self.drugStill.setObjectName("drugStill")
        self.drugGot = QtWidgets.QLabel(self.centralwidget)
        self.drugGot.setGeometry(QtCore.QRect(15, 290, 237, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.drugGot.setFont(font)
        self.drugGot.setObjectName("drugGot")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(255, 290, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setLineWidth(1)
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(255, 260, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setLineWidth(1)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(255, 230, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setLineWidth(1)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.drugNew = QtWidgets.QLabel(self.centralwidget)
        self.drugNew.setGeometry(QtCore.QRect(15, 230, 237, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.drugNew.setFont(font)
        self.drugNew.setObjectName("drugNew")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(220, 320, 200, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setLineWidth(1)
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.day_start = QtWidgets.QLabel(self.centralwidget)
        self.day_start.setGeometry(QtCore.QRect(15, 320, 200, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.day_start.setFont(font)
        self.day_start.setObjectName("day_start")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(350, 140, 160, 127))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setAutoFillBackground(False)
        self.listWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listWidget.setLineWidth(2)
        self.listWidget.setMidLineWidth(0)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidget.setObjectName("listWidget")
        self.select_meal_label = QtWidgets.QLabel(self.centralwidget)
        self.select_meal_label.setGeometry(QtCore.QRect(350, 110, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.select_meal_label.setFont(font)
        self.select_meal_label.setObjectName("select_meal_label")
        data_check.setCentralWidget(self.centralwidget)

        self.retranslateUi(data_check)
        QtCore.QMetaObject.connectSlotsByName(data_check)

        def close_window():
            data_check.close()
            
        self.add_back_pushButton.clicked.connect(close_window)
        self.next_pushButton.clicked.connect(lambda: self.open_encrypt_check(updated_data2))

    def open_encrypt_check(self,updated_data2):
        self.encrypt_check_window = QtWidgets.QMainWindow()
        self.encrypt_check_ui = Ui_encrypt_check()
        self.encrypt_check_ui.setupUi(self.encrypt_check_window, self.drug_List, self.each_drug, self.each_drug2, self.day_start, self.select_meal, self, {'drug_id': self.drug_id, **updated_data2})
        self.encrypt_check_window.show()
        

    def set_data_info(self, drug_id):
        self.drug_id = drug_id
        print(f"data_check {self.updated_data2}")

        # Fetch meal data for the given drug_id from the database
        connection = sqlite3.connect("medicine.db")
        cursor = connection.cursor()

        query = '''
            SELECT Meal.meal_name
            FROM Meal
            JOIN Drug_handle ON Meal.meal_id = Drug_handle.meal_id
            WHERE Drug_handle.drug_id = ?
        '''
        cursor.execute(query, (self.drug_id,))
        meal_data = cursor.fetchall()

        connection.close()
        
        # cursor.execute("SELECT * FROM Drug")
        # drugs = cursor.fetchall()
        # connection.close()
        # print(drugs)


        # Set the data in the labels and listWidget
        self.label_2.setText(f"{self.updated_data2['drugname']}")
        self.label_3.setText(f"{self.updated_data2['drugdescribe']}")
        self.label_4.setText(f"{self.updated_data2['drugall']}")
        self.label_5.setText(f"{self.updated_data2['drugone']}")
        self.label_6.setText(f"{self.updated_data2['drugnew']}")
        self.label_7.setText(f"{self.updated_data2['drugstill']}")
        self.label_8.setText(f"{self.updated_data2['druggot']}")
        self.label_9.setText(f"{self.updated_data2['day_start']}")

         # Clear the listWidget before adding new items
        self.listWidget.clear()

        # # Add meal selection data to the listWidget
        # meal_data = self.updated_data2.get('meals', [])
        # print(f"Meal Data: {meal_data}")
        # self.listWidget.addItems(meal_data)

         # Add fetched meal data to the listWidget
        meal_names = [item[0] for item in meal_data]
        self.listWidget.addItems(meal_names)

    def retranslateUi(self, data_check):
        _translate = QtCore.QCoreApplication.translate
        data_check.setWindowTitle(_translate("data_check", "ตรวจสอบความถูกต้อง"))
        self.label.setText(_translate("data_check", "ตรวจสอบความถูกต้อง"))
        self.add_back_pushButton.setText(_translate("data_check", "ย้อนกลับ"))
        self.label_4.setText(_translate("data_check", "ยาทั้งหมด"))
        self.label_2.setText(_translate("data_check", "ชื่อยา"))
        self.drugDescribe_label.setText(_translate("data_check", "คำอธิบายยา:"))
        self.drugAll_label.setText(_translate("data_check", "จำนวนยาทั้งหมดที่มี (เม็ด):"))
        self.label_3.setText(_translate("data_check", "คำอธิบายยา"))
        self.drugName_label.setText(_translate("data_check", "ชื่อยา:"))
        self.label_5.setText(_translate("data_check", "ยาที่กิน"))
        self.drugOne_label.setText(_translate("data_check", "จำนวนยาที่กินต่อ 1 มื้อ (เม็ด):"))
        self.next_pushButton.setText(_translate("data_check", "ถัดไป"))
        self.drugStill.setText(_translate("data_check", "จำนวนมื้อยาคงเหลือ (มื้อ):"))
        self.drugGot.setText(_translate("data_check", "จำนวนยาที่ได้รับมาแล้ว (เม็ด):"))
        self.label_8.setText(_translate("data_check", "ยาที่ได้รับมาแล้ว"))
        self.label_7.setText(_translate("data_check", "ยาคงเหลือ"))
        self.label_6.setText(_translate("data_check", "ยาที่ได้รับมาใหม่"))
        self.drugNew.setText(_translate("data_check", "จำนวนยาที่ได้รับมาใหม่ (เม็ด):"))
        self.label_9.setText(_translate("data_check", "วันที่"))
        self.day_start.setText(_translate("data_check", "วันแรกที่เริ่มรับประทานยา:"))
        self.select_meal_label.setText(_translate("data_check", "มื้อยาที่รับประทาน:"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    data_check = QtWidgets.QMainWindow()
    ui = Ui_data_check()
    ui.setupUi(data_check)
    data_check.show()
    sys.exit(app.exec_())
